// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorUC8upQElI9xJ4P2psyKqcL7kXkELh0',
    appId: '1:514992683018:web:5229a9eea020205a9947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    authDomain: 'expense-tracker-f5f8b.firebaseapp.com',
    databaseURL: 'https://expense-tracker-f5f8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
    measurementId: 'G-EBNFMPEW3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_v-Dt9NuUiwoEJV_vaGjDjnY3ZcjNrWs',
    appId: '1:514992683018:android:a96065676b1f88359947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    databaseURL: 'https://expense-tracker-f5f8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
  );
}
