// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorUC8upQElI9xJ4P2psyKqcL7kXkELh0',
    appId: '1:514992683018:web:5eadbae38c2009679947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    authDomain: 'expense-tracker-f5f8b.firebaseapp.com',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
    measurementId: 'G-YBWLC2GMCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_v-Dt9NuUiwoEJV_vaGjDjnY3ZcjNrWs',
    appId: '1:514992683018:android:3f67d656a57272569947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonPCND9-nEcucwKLGHcgIo9Kguwgixg8',
    appId: '1:514992683018:ios:f1aa507af8962dbd9947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
    iosClientId: '514992683018-ds56iukar4ob8g27pfh66cp2sotloddb.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBonPCND9-nEcucwKLGHcgIo9Kguwgixg8',
    appId: '1:514992683018:ios:3e9bf46a44f6f34d9947f3',
    messagingSenderId: '514992683018',
    projectId: 'expense-tracker-f5f8b',
    storageBucket: 'expense-tracker-f5f8b.appspot.com',
    iosClientId: '514992683018-f3b0u5bl4i06790nk28rf40com3uqoha.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
